import type { Ctx, Row, StockMove } from './db'
import { customerOutstanding, dispatchedQty, explodeBOM, lookupName, num, r2, receivedQty, rows, stockBalance, stockMatrix, supplierOutstanding, today } from './db'

export type FieldType = 'text' | 'number' | 'date' | 'select' | 'lookup' | 'textarea' | 'check' | 'computed' | 'password' | 'month' | 'time'
export type Lookup = { table: string; key: string; label: string; scope?: 'start'; filter?: (row: Row, header: Row) => boolean }
export type Field = {
  name: string; label: string; type: FieldType; options?: string[]; lookup?: Lookup; required?: boolean
  default?: unknown | ((ctx: Ctx) => unknown); compute?: (h: Row, lines: Row[], ctx: Ctx) => unknown; wide?: boolean; money?: boolean
  // Copy a value from the looked-up row when the lookup changes (e.g. machine hourly rate).
  fill?: Record<string, string>
}
export type Report = { params?: Field[]; run: (ctx: Ctx, params: Row) => { columns: string[]; rows: Row[] } }
export type FormDef = {
  // `tables` lists the spec's primary tables for display; `store` (default tables[0]) is where the header row is written.
  id: string; title: string; menu: string; tables: string[]; store?: string; key: string; prefix?: string; description: string
  fields: Field[]; lines?: { table: string; title: string; fields: Field[] }; scope?: 'start'; single?: boolean
  totals?: string[]; docDate?: string
  from?: Record<string, (src: Row, srcLines: Row[], ctx: Ctx) => { header: Row; lines?: Row[] }>
  stock?: (h: Row, lines: Row[], ctx: Ctx) => StockMove[]
  report?: Report; custom?: 'rights' | 'upload' | 'search' | 'misc'
  // Status roll-forward on linked documents after this document is saved (e.g. GRN → Inspected).
  after?: (h: Row, lines: Row[], ctx: Ctx) => void
}

const t = (name: string, label: string, o: Partial<Field> = {}): Field => ({ name, label, type: 'text', ...o })
const n = (name: string, label: string, o: Partial<Field> = {}): Field => ({ name, label, type: 'number', ...o })
const m = (name: string, label: string, o: Partial<Field> = {}): Field => ({ name, label, type: 'number', money: true, ...o })
const d = (name: string, label: string, o: Partial<Field> = {}): Field => ({ name, label, type: 'date', default: () => today(), ...o })
const s = (name: string, label: string, options: string[], o: Partial<Field> = {}): Field => ({ name, label, type: 'select', options, default: options[0], ...o })
const ta = (name: string, label: string, o: Partial<Field> = {}): Field => ({ name, label, type: 'textarea', wide: true, ...o })
const ck = (name: string, label: string, o: Partial<Field> = {}): Field => ({ name, label, type: 'check', default: false, ...o })
const c = (name: string, label: string, compute: Field['compute'], o: Partial<Field> = {}): Field => ({ name, label, type: 'computed', compute, ...o })
const lk = (name: string, label: string, table: string, key: string, lbl: string, o: Partial<Field> = {}): Field => ({ name, label, type: 'lookup', lookup: { table, key, label: lbl }, ...o })

const item = (name = 'Item', label = 'Item', o: Partial<Field> = {}) => lk(name, label, 'Item', 'ItemId', 'ItemName', { required: true, fill: { UOM: 'UOM', Rate: 'Rate' }, ...o })
const customer = (o: Partial<Field> = {}) => lk('Customer', 'Customer', 'Customer', 'CustId', 'CustName', { required: true, ...o })
const supplier = (o: Partial<Field> = {}) => lk('Supplier', 'Supplier', 'SUPPLIER', 'SuppId', 'SuppName', { required: true, ...o })
const vendor = (o: Partial<Field> = {}) => lk('Vendor', 'Subcontractor', 'Vendor', 'VendorId', 'VendorName', { required: true, ...o })
const machine = (name = 'Machine', label = 'Machine') => lk(name, label, 'Machine', 'Id', 'MachineName', { fill: { HourlyRate: 'HourlyRate' } })
const process = (name = 'Process', label = 'Process') => lk(name, label, 'ProcessID', 'ProcID', 'ProcessName')
const store = (name: string, label: string, def: string) => lk(name, label, 'Stores', 'storeID', 'StoreName', { required: true, default: def })
const staff = (name = 'Employee', label = 'Employee') => lk(name, label, 'STAFF', 'Id', 'EmpName', { required: true })
const ref = (name: string, label: string, table: string, key: string, lbl: string, o: Partial<Field> = {}) => lk(name, label, table, key, lbl, o)
const uom = () => lk('UOM', 'UOM', 'Measurement', 'Id', 'UOMName')
const status = (options: string[]) => s('Status', 'Status', options)

const sum = (lines: Row[], f: string) => r2(lines.reduce((acc, l) => acc + num(l[f]), 0))
const amount = c('Amount', 'Amount', l => r2(num(l.Qty) * num(l.Rate)), { money: true })
const qtyRateLines = [item(), t('Description', 'Description'), n('Qty', 'Qty', { required: true, default: 1 }), uom(), m('Rate', 'Rate'), amount]
const gstTotals = [
  c('SubTotal', 'Sub Total', (_, lines) => sum(lines, 'Amount'), { money: true }),
  c('GSTAmount', 'GST Amount', h => r2(num(h.SubTotal) * num(h.GST) / 100), { money: true }),
  c('GrandTotal', 'Grand Total', h => r2(num(h.SubTotal) + num(h.GSTAmount) + num(h.Freight)), { money: true }),
]
const setStatus = (ctx: Ctx, table: string, key: string, id: unknown, status: string) => { const r = id ? rows(ctx.db, table).find(x => x[key] === id) : undefined; if (r) r.Status = status }
const copyLines = (lines: Row[], map: (l: Row) => Row) => lines.map(l => ({ ...map(l) }))
const moves = (lines: Row[], itemField: string, qtyField: string, storeID: string, sign: 1 | -1): StockMove[] =>
  lines.filter(l => l[itemField] && num(l[qtyField]) > 0).map(l => ({ ItemId: l[itemField], storeID, Qty: sign * num(l[qtyField]) }))

export const MENUS = ['Security', 'Masters', 'Sales', 'PPC', 'SubContract', 'Purchase', 'Stores', 'Dispatch', 'Quality', 'Maintenance', 'HR & Payroll', 'Finance', 'Others'] as const

export const FORMS: FormDef[] = [
  // ───────── Security & setup (DBStart.mdb)
  { id: 'frmUserEntry', title: 'User Account Creation', menu: 'Security', scope: 'start', tables: ['user1'], key: 'UserId', description: 'User account creation, modification & password management.',
    fields: [t('UserId', 'User Id', { required: true }), t('UserName', 'User Name', { required: true }), { name: 'Password', label: 'Password (5 char)', type: 'password', required: true }, t('Designation', 'Designation'), ck('Active', 'Active', { default: true })] },
  { id: 'frmUserRights', title: 'User Permission Security Matrix', menu: 'Security', scope: 'start', tables: ['userrights'], key: 'UserId', description: 'Configure the 79 granular module permission flags per user.', fields: [], custom: 'rights' },
  { id: 'frmViewUserScreens', title: 'Active Session Monitor', menu: 'Security', scope: 'start', tables: ['Logs', 'OnLineUsers'], key: 'entryID', description: 'Active session audit & online user status.', fields: [],
    report: { run: ctx => ({ columns: ['Time', 'UserId', 'Action', 'Form', 'Detail'], rows: ctx.start.Logs.map(l => ({ ...l, Time: new Date(l.Time).toLocaleString('en-IN') })) }) } },
  { id: 'frmCompMaster', title: 'Company Master Profile', menu: 'Security', scope: 'start', tables: ['CompMaster'], key: 'CustId', single: true, description: 'Company profile and default financial year.',
    fields: [t('CompName', 'Company Name', { required: true }), t('Address', 'Address', { wide: true }), t('City', 'City'), t('State', 'State'), t('PIN', 'PIN'), t('GSTIN', 'GSTIN'), t('PAN', 'PAN'), t('Phone', 'Phone'), t('Email', 'Email'), t('Currency', 'Base Currency', { default: 'INR' }), s('FinYear', 'Default Financial Year', ['2026-27', '2025-26', '2024-25'])] },
  // ───────── Masters
  { id: 'frmCategory', title: 'Item Group / Category Master', menu: 'Masters', tables: ['CATEGORY'], key: 'Id', description: 'Item groups and categories.', fields: [t('Id', 'Category Code', { required: true }), t('CategoryName', 'Category Name', { required: true }), t('Description', 'Description', { wide: true })] },
  { id: 'frmItem', title: 'Item Master Definition', menu: 'Masters', tables: ['Item', 'ItemSub'], key: 'ItemId', description: 'Raw materials, component parts, assemblies and hardware.',
    fields: [t('ItemId', 'Item Code', { required: true }), t('ItemName', 'Item Name', { required: true }), lk('Category', 'Category', 'CATEGORY', 'Id', 'CategoryName', { required: true }), s('ItemType', 'Item Type', ['Raw Material', 'Component', 'Sub-Assembly', 'Assembly', 'Hardware', 'Consumable', 'Tool']), uom(), m('Rate', 'Std Rate'), n('WeightKg', 'Unit Weight (Kg)'), t('HSN', 'HSN Code'), n('GST', 'GST %', { default: 18 }), n('ReorderLevel', 'Reorder Level'), t('DrawingNo', 'Drawing No'), t('RevLevel', 'Rev Level'),
      c('StockAll', 'Stock (all stores)', (h, _l, ctx) => stockBalance(ctx.db, h.ItemId))] },
  { id: 'frmItemAssign', title: 'Item Cross Reference Mapping', menu: 'Masters', tables: ['ItemAssign', 'Party'], key: 'Id', prefix: 'IA', description: 'Customer / supplier part number aliases.',
    fields: [item(), s('PartyType', 'Party Type', ['Customer', 'Supplier']), t('Party', 'Party Code', { required: true }), t('PartyPartNo', 'Party Part No', { required: true }), t('Description', 'Alias Description', { wide: true })] },
  { id: 'frmMiscMore', title: 'Extended Technical Details', menu: 'Masters', tables: ['ItemSub', 'itm_legend'], key: 'ItemId', description: 'Engineering drawing, revision and technical specifications.',
    fields: [item('ItemId', 'Item'), t('DrawingNo', 'Drawing No'), t('RevLevel', 'Rev Level'), t('MaterialSpec', 'Material Specification'), t('SurfaceFinish', 'Surface Finish'), t('HeatTreatment', 'Heat Treatment'), t('Tolerance', 'General Tolerance'), t('Hardness', 'Hardness'), ta('Remarks', 'Remarks')] },
  { id: 'frmAutoFillBOMList', title: 'Multi-Level BOM Explosion', menu: 'Masters', tables: ['AssmblyDef', 'ItemSub'], key: 'Id', prefix: 'BOM', description: 'Product structure: parent assembly → sub-assemblies, components, raw materials.',
    fields: [item('ParentItem', 'Parent Assembly'), t('Description', 'Description', { wide: true }), t('Rev', 'Rev', { default: 'A' }), d('Date', 'Date'), status(['Active', 'Draft', 'Archived'])],
    lines: { table: 'AssmblyDefSub', title: 'Child components', fields: [item('ChildItem', 'Child Item', { fill: { UOM: 'UOM' } }), n('QtyPer', 'Qty per Assembly', { required: true, default: 1 }), uom(), s('Level', 'Type', ['Manufactured', 'Bought-out', 'Raw Material', 'Sub-Assembly']), n('ScrapPct', 'Scrap %')] } },
  { id: 'frmUploadAssembly', title: 'BOM Import & Assembly Upload', menu: 'Masters', tables: ['AssmblyDef'], key: 'Id', description: 'Bulk BOM upload (CSV: Parent, Child, QtyPer, UOM, Type).', fields: [], custom: 'upload' },
  { id: 'frmMeasure', title: 'Unit of Measurement Master', menu: 'Masters', tables: ['Measurement'], key: 'Id', description: 'UOM codes.', fields: [t('Id', 'UOM Code', { required: true }), t('UOMName', 'UOM Name', { required: true })] },
  { id: 'frmProcessID', title: 'Operation / Process Master', menu: 'Masters', tables: ['ProcessID'], key: 'ProcID', description: 'Machining, heat treatment, plating, QC operations.',
    fields: [t('ProcID', 'Process Id', { required: true }), t('ProcessName', 'Process Name', { required: true }), s('ProcessType', 'Type', ['Machining', 'Heat Treatment', 'Plating', 'QC', 'Assembly', 'Grinding', 'Welding', 'Other']), n('StdTimeMin', 'Std Time (min)'), m('RatePerHr', 'Rate / Hr'), s('Mode', 'Mode', ['In-house', 'Subcontract'])] },
  { id: 'frmMachine', title: 'Machine & Equipment Master', menu: 'Masters', tables: ['Machine'], key: 'Id', description: 'Capacity, hourly rates and work centers.',
    fields: [t('Id', 'Machine Code', { required: true }), t('MachineName', 'Machine Name', { required: true }), t('WorkCenter', 'Work Center'), n('CapacityHrsPerDay', 'Capacity Hrs / Day', { default: 20 }), m('HourlyRate', 'Hourly Rate'), t('Make', 'Make'), t('Model', 'Model'), s('Status', 'Status', ['Operational', 'Under Maintenance', 'Breakdown', 'Idle'])] },
  { id: 'frmStores', title: 'Warehouse & Store Location', menu: 'Masters', tables: ['Stores', 'STORE'], key: 'storeID', description: 'RM, WIP, FG, SubCon, Quarantine, Scrap and Tool Crib locations.',
    fields: [t('storeID', 'Store Id', { required: true }), t('StoreName', 'Store Name', { required: true }), s('StoreType', 'Store Type', ['RM', 'Production', 'FG', 'SubCon', 'Quarantine', 'Scrap', 'Tool Crib']), t('Location', 'Location')] },
  { id: 'frmCustomer', title: 'Customer Master Register', menu: 'Masters', tables: ['Customer', 'CustomerIndirect'], key: 'CustId', description: 'Party name, addresses, GSTIN and payment terms.',
    fields: [t('CustId', 'Customer Id', { required: true }), t('CustName', 'Customer Name', { required: true }), t('Address', 'Address', { wide: true }), t('City', 'City'), t('State', 'State'), t('GSTIN', 'GSTIN'), t('PAN', 'PAN'), t('ContactPerson', 'Contact Person'), t('Phone', 'Phone'), t('Email', 'Email'), n('PaymentTerms', 'Payment Terms (days)', { default: 30 }), m('CreditLimit', 'Credit Limit'), lk('Currency', 'Currency', 'CurrencyType', 'Id', 'CurrencyName', { default: 'INR' }), m('OpeningBalance', 'Opening Balance'),
      c('Outstanding', 'Outstanding Balance', (h, _l, ctx) => customerOutstanding(ctx.db, h.CustId), { money: true })] },
  { id: 'frmSupplier', title: 'Supplier / Vendor Register', menu: 'Masters', tables: ['SUPPLIER', 'Vendor'], key: 'SuppId', description: 'Material supplier master.',
    fields: [t('SuppId', 'Supplier Id', { required: true }), t('SuppName', 'Supplier Name', { required: true }), s('SupplierType', 'Type', ['Material Supplier', 'Subcontractor', 'Both', 'Service']), t('Address', 'Address', { wide: true }), t('City', 'City'), t('State', 'State'), t('GSTIN', 'GSTIN'), t('ContactPerson', 'Contact Person'), t('Phone', 'Phone'), n('PaymentTerms', 'Payment Terms (days)', { default: 30 }), m('OpeningBalance', 'Opening Balance'),
      c('Outstanding', 'Outstanding Balance', (h, _l, ctx) => supplierOutstanding(ctx.db, 'Supplier', h.SuppId), { money: true })] },
  { id: 'frmVendor', title: 'Subcontractor Vendor Master', menu: 'Masters', tables: ['Vendor'], key: 'VendorId', description: 'Job-work subcontractors.',
    fields: [t('VendorId', 'Vendor Id', { required: true }), t('VendorName', 'Vendor Name', { required: true }), t('Processes', 'Processes Offered', { wide: true }), t('Address', 'Address', { wide: true }), t('City', 'City'), t('State', 'State'), t('GSTIN', 'GSTIN'), t('ContactPerson', 'Contact Person'), t('Phone', 'Phone'), n('PaymentTerms', 'Payment Terms (days)', { default: 15 }), m('OpeningBalance', 'Opening Balance'),
      c('Outstanding', 'Outstanding Balance', (h, _l, ctx) => supplierOutstanding(ctx.db, 'Vendor', h.VendorId), { money: true })] },
  { id: 'frmCurrency', title: 'Multi-Currency Setup', menu: 'Masters', tables: ['CurrencyType'], key: 'Id', description: 'INR, USD, EUR, GBP.', fields: [t('Id', 'Currency Code', { required: true }), t('CurrencyName', 'Currency Name', { required: true }), t('Symbol', 'Symbol')] },
  { id: 'frmCurrToday', title: 'Daily Exchange Rate Entry', menu: 'Masters', tables: ['CurrencyToday'], key: 'Id', prefix: 'FX', description: 'Daily exchange rates.', fields: [d('Date', 'Date'), lk('Currency', 'Currency', 'CurrencyType', 'Id', 'CurrencyName', { required: true }), n('RateINR', 'Rate in INR', { required: true })] },
  { id: 'frmCostCenter', title: 'Cost Center Setup', menu: 'Masters', tables: ['CostCenter'], key: 'CostCntrId', description: 'Departmental accounting cost centers.', fields: [t('CostCntrId', 'Cost Center Id', { required: true }), t('CostCenterName', 'Cost Center Name', { required: true }), t('Department', 'Department'), m('Budget', 'Annual Budget')] },
  { id: 'frmBanks', title: 'Bank Account Master', menu: 'Masters', tables: ['Banks', 'Bank'], key: 'Id', description: 'Company bank accounts.',
    fields: [t('Id', 'Bank Id', { required: true }), t('BankName', 'Bank Name', { required: true }), t('Branch', 'Branch'), t('AccountNo', 'Account No'), t('IFSC', 'IFSC'), s('AccountType', 'Account Type', ['Current', 'Savings', 'CC/OD']), m('OpeningBalance', 'Opening Balance'),
      c('Balance', 'Book Balance', (h, _l, ctx) => r2(num(h.OpeningBalance) + rows(ctx.db, 'BankTrans').filter(b => b.Bank === h.Id).reduce((acc, b) => acc + (['Deposit', 'Cheque Deposit', 'Interest'].includes(b.TxnType) ? num(b.Amount) : -num(b.Amount)), 0)), { money: true })] },
  // ───────── Sales & order fulfilment
  { id: 'frmEnquiry', title: 'Customer Sales Enquiry', menu: 'Sales', tables: ['Enquiry', 'EnquirySub'], key: 'Id', prefix: 'ENQ', docDate: 'EnqDate', description: 'Customer details, requested items, quantities and delivery deadlines.',
    fields: [d('EnqDate', 'Enquiry Date'), customer(), t('ContactPerson', 'Contact Person'), t('CustRef', 'Customer Ref / RFQ No'), d('DeliveryDeadline', 'Delivery Deadline', { default: undefined }), s('Source', 'Source', ['Email', 'Phone', 'Portal', 'Visit']), status(['Open', 'Estimated', 'Quoted', 'Converted', 'Lost']), ta('Remarks', 'Remarks')],
    lines: { table: 'EnquirySub', title: 'Requested items', fields: [item(), t('Description', 'Description / Spec'), n('Qty', 'Qty', { required: true, default: 1 }), uom(), m('TargetRate', 'Target Rate'), d('RequiredBy', 'Required By', { default: undefined })] } },
  { id: 'frmEstimation', title: 'Costing & Price Estimation', menu: 'Sales', tables: ['Estimate', 'EstimateSub'], key: 'Id', prefix: 'EST', docDate: 'Date', description: 'RM cost (weight × rate) + operations (time × machine hourly rate) + treatments + packing & transport + overhead + profit.',
    fields: [d('Date', 'Date'), customer(), ref('EnquiryRef', 'Enquiry Ref', 'Enquiry', 'Id', 'CustRef'), item(), n('Qty', 'Order Qty', { default: 1 }), n('RMWeightKg', 'RM Weight / pc (Kg)'), m('RMRatePerKg', 'RM Rate / Kg'),
      c('RMCost', 'RM Cost / pc', h => r2(num(h.RMWeightKg) * num(h.RMRatePerKg)), { money: true }), c('MachiningCost', 'Operation Cost / pc', (_, l) => sum(l, 'Cost'), { money: true }),
      m('SurfaceTreatment', 'Surface Treatment / pc'), m('HeatTreatment', 'Heat Treatment / pc'), m('Packing', 'Packing / pc'), m('Transport', 'Transport / pc'), n('OverheadPct', 'Overhead %', { default: 10 }), n('ProfitPct', 'Profit %', { default: 15 }),
      c('TotalCost', 'Total Cost / pc', h => r2(num(h.RMCost) + num(h.MachiningCost) + num(h.SurfaceTreatment) + num(h.HeatTreatment) + num(h.Packing) + num(h.Transport)), { money: true }),
      c('UnitPrice', 'Estimated Unit Price', h => r2(num(h.TotalCost) * (1 + num(h.OverheadPct) / 100) * (1 + num(h.ProfitPct) / 100)), { money: true }),
      c('OrderValue', 'Estimated Order Value', h => r2(num(h.UnitPrice) * num(h.Qty)), { money: true }), status(['Draft', 'Approved', 'Quoted'])],
    lines: { table: 'EstimateSub', title: 'Operations', fields: [process(), machine(), n('TimeMin', 'Process Time (min)', { required: true }), m('HourlyRate', 'Machine Hourly Rate'), c('Cost', 'Operation Cost', l => r2(num(l.TimeMin) / 60 * num(l.HourlyRate)), { money: true })] },
    from: { frmEnquiry: (src, lines) => ({ header: { Customer: src.Customer, EnquiryRef: src.Id, Item: lines[0]?.Item, Qty: lines[0]?.Qty ?? 1 } }) },
    after: (h, _l, ctx) => setStatus(ctx, 'Enquiry', 'Id', h.EnquiryRef, 'Estimated') },
  { id: 'frmQuote', title: 'Sales Quotation Generation', menu: 'Sales', tables: ['QUOTE', 'QuoteSub'], key: 'QuoteId', prefix: 'QT', docDate: 'Date', description: 'Quotation with valid-till date, payment terms, GST and terms & conditions.',
    fields: [d('Date', 'Quote Date'), customer(), ref('EnquiryRef', 'Enquiry Ref', 'Enquiry', 'Id', 'CustRef'), ref('EstimateRef', 'Estimate Ref', 'Estimate', 'Id', 'Item'), d('ValidTill', 'Valid Till', { default: undefined }), t('PaymentTerms', 'Payment Terms', { default: '30 days from invoice' }), t('DeliveryTerms', 'Delivery Terms', { default: 'Ex-works' }), lk('Currency', 'Currency', 'CurrencyType', 'Id', 'CurrencyName', { default: 'INR' }), n('GST', 'GST %', { default: 18 }), ...gstTotals, status(['Draft', 'Sent', 'Accepted', 'Rejected', 'Converted']), ta('Terms', 'Terms & Conditions', { default: 'Prices valid till the date mentioned. Delivery ex-works. Payment as per terms.' })],
    lines: { table: 'QuoteSub', title: 'Quoted items', fields: qtyRateLines },
    from: {
      frmEnquiry: (src, lines) => ({ header: { Customer: src.Customer, EnquiryRef: src.Id }, lines: copyLines(lines, l => ({ Item: l.Item, Description: l.Description, Qty: l.Qty, UOM: l.UOM, Rate: l.TargetRate })) }),
      frmEstimation: src => ({ header: { Customer: src.Customer, EnquiryRef: src.EnquiryRef, EstimateRef: src.Id }, lines: [{ Item: src.Item, Qty: src.Qty, Rate: src.UnitPrice }] }),
    },
    after: (h, _l, ctx) => { setStatus(ctx, 'Enquiry', 'Id', h.EnquiryRef, 'Quoted'); setStatus(ctx, 'Estimate', 'Id', h.EstimateRef, 'Quoted') } },
  { id: 'frmMfgPO', title: 'Customer Purchase Order', menu: 'Sales', tables: ['MfgPO', 'MfgPOSub', 'MfgPOTrack'], key: 'POId', prefix: 'SO', docDate: 'PODate', description: 'Customer PO / sales order confirmation. Dispatch tracking via MfgPOTrack.',
    fields: [d('PODate', 'PO Date'), customer(), t('CustPONo', 'Customer PO No', { required: true }), ref('QuoteRef', 'Quotation Ref', 'QUOTE', 'QuoteId', 'Customer'), d('DeliveryDate', 'Delivery Date', { default: undefined }), t('PaymentTerms', 'Payment Terms', { default: '30 days' }), n('GST', 'GST %', { default: 18 }), ...gstTotals, status(['Open', 'In Production', 'Partially Dispatched', 'Closed', 'Cancelled'])],
    lines: { table: 'MfgPOSub', title: 'Ordered items', fields: [...qtyRateLines, d('LineDelivery', 'Delivery Date', { default: undefined }), c('Dispatched', 'Dispatched', (l, _x, ctx) => dispatchedQty(ctx.db, l.ParentId, l.Item)), c('Pending', 'Pending', (l, _x, ctx) => r2(num(l.Qty) - dispatchedQty(ctx.db, l.ParentId, l.Item)))] },
    from: { frmQuote: (src, lines) => ({ header: { Customer: src.Customer, QuoteRef: src.QuoteId, GST: src.GST, PaymentTerms: src.PaymentTerms }, lines: copyLines(lines, l => ({ Item: l.Item, Description: l.Description, Qty: l.Qty, UOM: l.UOM, Rate: l.Rate })) }) },
    after: (h, _l, ctx) => { setStatus(ctx, 'QUOTE', 'QuoteId', h.QuoteRef, 'Converted'); const q = rows(ctx.db, 'QUOTE').find(x => x.QuoteId === h.QuoteRef); if (q) setStatus(ctx, 'Enquiry', 'Id', q.EnquiryRef, 'Converted') } },
  { id: 'frmViewPODetails', title: 'Customer PO Status Monitor', menu: 'Sales', tables: ['MfgPOTrack'], key: 'POId', description: 'Ordered vs dispatched vs pending per PO line.', fields: [],
    report: { run: ctx => ({ columns: ['POId', 'CustPONo', 'Customer', 'Item', 'Ordered', 'Dispatched', 'Pending', 'DeliveryDate', 'Status'],
      rows: rows(ctx.db, 'MfgPOSub').map(l => { const po = rows(ctx.db, 'MfgPO').find(p => p.POId === l.ParentId) || {}; const disp = dispatchedQty(ctx.db, l.ParentId, l.Item); return { POId: l.ParentId, CustPONo: po.CustPONo, Customer: lookupName(ctx.db, 'Customer', 'CustId', 'CustName', po.Customer), Item: l.Item, Ordered: l.Qty, Dispatched: disp, Pending: r2(num(l.Qty) - disp), DeliveryDate: l.LineDelivery || po.DeliveryDate, Status: po.Status } }) }) } },
  // ───────── PPC
  { id: 'frmAssmReqAnaly', title: 'Assembly Requirements', menu: 'PPC', tables: ['AssmblyDef', 'MatlIssNote'], key: 'Id', description: 'Multi-level assembly explosion against stock.', fields: [],
    report: { params: [item('Item', 'Assembly'), n('Qty', 'Required Qty', { default: 1 })], run: (ctx, p) => ({ columns: ['Level', 'ItemId', 'ItemName', 'Type', 'Required', 'Stock', 'Shortage'],
      rows: explodeBOM(ctx.db, p.Item, num(p.Qty) || 1).map(r => { const stock = stockBalance(ctx.db, r.ItemId); return { ...r, ItemName: lookupName(ctx.db, 'Item', 'ItemId', 'ItemName', r.ItemId), Required: r.Qty, Stock: stock, Shortage: Math.max(0, r2(r.Qty - stock)) } }) }) } },
  { id: 'frmMatReqAnaly', title: 'MRP Material Requirements', menu: 'PPC', tables: ['MatlIssNote', 'MatlIssNoteSub'], key: 'Id', description: 'Open customer PO pending qty exploded through BOM vs available STORE stock → shortages.', fields: [],
    report: { run: ctx => { const need = new Map<string, number>(); rows(ctx.db, 'MfgPOSub').forEach(l => { const po = rows(ctx.db, 'MfgPO').find(p => p.POId === l.ParentId); if (!po || ['Closed', 'Cancelled'].includes(po.Status)) return; const pending = num(l.Qty) - dispatchedQty(ctx.db, l.ParentId, l.Item); if (pending <= 0) return; const exploded = explodeBOM(ctx.db, l.Item, pending); (exploded.length ? exploded : [{ ItemId: l.Item, Qty: pending }]).forEach(e => need.set(e.ItemId, (need.get(e.ItemId) || 0) + e.Qty)) })
      return { columns: ['ItemId', 'ItemName', 'ItemType', 'Required', 'Stock', 'Shortage', 'Action'], rows: [...need.entries()].map(([ItemId, Required]) => { const it = rows(ctx.db, 'Item').find(i => i.ItemId === ItemId) || {}; const stock = stockBalance(ctx.db, ItemId); const short = Math.max(0, r2(Required - stock)); return { ItemId, ItemName: it.ItemName, ItemType: it.ItemType, Required: r2(Required), Stock: stock, Shortage: short, Action: short ? (it.ItemType === 'Raw Material' || it.ItemType === 'Hardware' ? 'Raise Purchase PO' : 'Schedule Production') : 'OK' } }) } } } },
  { id: 'frmPlanProdCapacity', title: 'Machine Capacity Planning', menu: 'PPC', tables: ['PlanProdCapa', 'Machine'], key: 'Id', description: 'Required machine hours from open schedules vs available capacity.', fields: [],
    report: { params: [n('WorkingDays', 'Working Days', { default: 26 })], run: (ctx, p) => ({ columns: ['Machine', 'MachineName', 'WorkCenter', 'CapacityHrs', 'PlannedHrs', 'LoadPct', 'Remark'],
      rows: rows(ctx.db, 'Machine').map(mc => { const open = rows(ctx.db, 'ProdSchd').filter(sc => sc.Status !== 'Completed').map(sc => sc.Id); const planned = rows(ctx.db, 'ProdSchdSub').filter(l => open.includes(l.ParentId) && l.Machine === mc.Id).reduce((acc, l) => acc + num(l.PlannedHrs), 0); const cap = num(mc.CapacityHrsPerDay) * (num(p.WorkingDays) || 26); const load = cap ? r2(planned / cap * 100) : 0; return { Machine: mc.Id, MachineName: mc.MachineName, WorkCenter: mc.WorkCenter, CapacityHrs: cap, PlannedHrs: r2(planned), LoadPct: load, Remark: load > 100 ? 'BOTTLENECK' : load > 85 ? 'Near capacity' : 'Available' } }) }) } },
  { id: 'frmPlanY', title: 'Yearly Master Planning', menu: 'PPC', tables: ['planchart'], key: 'Id', prefix: 'PLAN', description: 'Master production plan chart by month.',
    fields: [t('PlanYear', 'Plan Year', { required: true, default: (ctx: Ctx) => ctx.db.year }), item(), n('AnnualQty', 'Annual Plan Qty'), c('Planned', 'Planned Total', (_, l) => sum(l, 'PlannedQty')), status(['Draft', 'Approved'])],
    lines: { table: 'planchartSub', title: 'Monthly plan', fields: [s('Month', 'Month', ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']), n('PlannedQty', 'Planned Qty'), t('Remarks', 'Remarks')] } },
  { id: 'frmProdSchedule', title: 'Production Scheduling', menu: 'PPC', tables: ['ProdSchd', 'ProdSchdSub'], key: 'Id', prefix: 'SCH', docDate: 'Date', description: 'Work center schedules and job card allocation.',
    fields: [d('Date', 'Schedule Date'), ref('MfgPORef', 'Customer PO Ref', 'MfgPO', 'POId', 'CustPONo'), item(), n('Qty', 'Schedule Qty', { required: true, default: 1 }), d('StartDate', 'Start Date'), d('EndDate', 'End Date', { default: undefined }), c('TotalHrs', 'Total Planned Hrs', (_, l) => sum(l, 'PlannedHrs')), status(['Planned', 'Released', 'In Progress', 'Completed'])],
    lines: { table: 'ProdSchdSub', title: 'Operation schedule', fields: [process(), machine(), n('PlannedHrs', 'Planned Hrs', { required: true }), staff('Operator', 'Operator'), d('OpDate', 'Date')] },
    from: { frmMfgPO: (src, lines) => ({ header: { MfgPORef: src.POId, Item: lines[0]?.Item, Qty: lines[0]?.Qty, EndDate: src.DeliveryDate } }) } },
  { id: 'frmProdnWOIssue', title: 'Job Card / IWO Issue', menu: 'PPC', tables: ['ProdnIWOIss', 'ProdnIWOissSub'], key: 'Id', prefix: 'IWO', docDate: 'Date', description: 'Release Internal Work Orders (job cards) to machines / operators.',
    fields: [d('Date', 'Issue Date'), ref('ScheduleRef', 'Schedule Ref', 'ProdSchd', 'Id', 'Item'), ref('MfgPORef', 'Customer PO Ref', 'MfgPO', 'POId', 'CustPONo'), item(), n('Qty', 'Order Qty', { required: true, default: 1 }), staff('Operator', 'Operator'), d('TargetDate', 'Target Date', { default: undefined }), status(['Issued', 'In Progress', 'Completed', 'Closed'])],
    lines: { table: 'ProdnIWOissSub', title: 'Operations on job card', fields: [process(), machine(), n('Qty', 'Qty', { default: 1 }), t('Remarks', 'Remarks')] },
    from: { frmProdSchedule: (src, lines) => ({ header: { ScheduleRef: src.Id, MfgPORef: src.MfgPORef, Item: src.Item, Qty: src.Qty, TargetDate: src.EndDate }, lines: copyLines(lines, l => ({ Process: l.Process, Machine: l.Machine, Qty: src.Qty })) }) },
    after: (h, _l, ctx) => { setStatus(ctx, 'ProdSchd', 'Id', h.ScheduleRef, 'In Progress'); setStatus(ctx, 'MfgPO', 'POId', h.MfgPORef, 'In Production') } },
  { id: 'frmProdn', title: 'Shop Floor Production Log', menu: 'PPC', tables: ['DailyProd', 'DailyProdsub', 'DailyProdHeadsEff'], key: 'Id', prefix: 'DP', docDate: 'Date', description: 'Produced / accepted / rejected quantity, setup and run time per shift.',
    fields: [d('Date', 'Production Date'), s('Shift', 'Shift', ['First', 'Second', 'Night']), machine(), staff('Operator', 'Operator'), ref('IWORef', 'IWO / Job Card', 'ProdnIWOIss', 'Id', 'Item'), c('TotalAccepted', 'Total Accepted', (_, l) => sum(l, 'AcceptedQty')), c('TotalRejected', 'Total Rejected', (_, l) => sum(l, 'RejectedQty')), c('Efficiency', 'Efficiency %', (_, l) => { const run = sum(l, 'RunMin'); const total = run + sum(l, 'SetupMin'); return total ? r2(run / total * 100) : 0 })],
    lines: { table: 'DailyProdsub', title: 'Output', fields: [item(), process(), n('ProducedQty', 'Produced'), n('AcceptedQty', 'Accepted'), n('RejectedQty', 'Rejected'), n('SetupMin', 'Setup (min)'), n('RunMin', 'Run (min)')] },
    from: { frmProdnWOIssue: (src, lines) => ({ header: { IWORef: src.Id, Operator: src.Operator, Machine: lines[0]?.Machine }, lines: copyLines(lines, l => ({ Item: src.Item, Process: l.Process })) }) } },
  { id: 'frmProdnWOReturn', title: 'Job Card / IWO Return', menu: 'PPC', tables: ['ProdnIWORet', 'ProdnIWORetSub'], key: 'Id', prefix: 'IWR', docDate: 'Date', description: 'Close job card; accepted qty moves to Finished Goods / Inspection store.',
    fields: [d('Date', 'Return Date'), ref('IWORef', 'IWO / Job Card', 'ProdnIWOIss', 'Id', 'Item', { required: true }), store('ToStore', 'Return To Store', 'FG'), c('TotalAccepted', 'Total Accepted', (_, l) => sum(l, 'AcceptedQty')), c('TotalRejected', 'Total Rejected', (_, l) => sum(l, 'RejectedQty')), status(['Returned', 'Closed'])],
    lines: { table: 'ProdnIWORetSub', title: 'Returned items', fields: [item(), n('ProducedQty', 'Produced'), n('AcceptedQty', 'Accepted', { required: true }), n('RejectedQty', 'Rejected'), t('Remarks', 'Remarks')] },
    stock: (h, lines) => [...moves(lines, 'Item', 'AcceptedQty', h.ToStore, 1), ...moves(lines, 'Item', 'RejectedQty', 'SCRAP', 1)],
    from: { frmProdnWOIssue: src => ({ header: { IWORef: src.Id }, lines: [{ Item: src.Item, ProducedQty: src.Qty, AcceptedQty: src.Qty, RejectedQty: 0 }] }) },
    after: (h, _l, ctx) => { setStatus(ctx, 'ProdnIWOIss', 'Id', h.IWORef, 'Completed'); const iwo = rows(ctx.db, 'ProdnIWOIss').find(x => x.Id === h.IWORef); if (iwo) setStatus(ctx, 'ProdSchd', 'Id', iwo.ScheduleRef, 'Completed') } },
  // ───────── Subcontracting
  { id: 'frmSubConPO', title: 'Subcontract PO Outward', menu: 'SubContract', tables: ['SubConPO', 'SubConPOSub', 'SubConPOTrack'], key: 'POId', prefix: 'SCPO', docDate: 'Date', description: 'Job-work PO to subcontractor for external operations.',
    fields: [d('Date', 'PO Date'), vendor(), ref('IWORef', 'IWO Ref', 'ProdnIWOIss', 'Id', 'Item'), d('DeliveryDate', 'Delivery Date', { default: undefined }), n('GST', 'GST %', { default: 18 }), ...gstTotals, status(['Open', 'Material Sent', 'Received', 'Closed'])],
    lines: { table: 'SubConPOSub', title: 'Job work items', fields: [item(), process(), n('Qty', 'Qty', { required: true, default: 1 }), uom(), m('Rate', 'Job Work Rate'), amount] },
    from: { frmProdnWOIssue: (src, lines, ctx) => ({ header: { IWORef: src.Id }, lines: [{ Item: src.Item, Process: lines.find(l => rows(ctx.db, 'ProcessID').find(p => p.ProcID === l.Process)?.Mode === 'Subcontract')?.Process, Qty: src.Qty }] }) } },
  { id: 'frmDCSubConOut', title: 'Subcontract Outward DC', menu: 'SubContract', tables: ['DCSubConOutgoing', 'DcSubConOutgoingSub'], key: 'DcId', prefix: 'SCDC-O', docDate: 'Date', description: 'Issue material to subcontractor. Stock moves From Store → SubCon Store.',
    fields: [d('Date', 'DC Date'), vendor(), ref('SubConPORef', 'Subcontract PO', 'SubConPO', 'POId', 'Vendor'), store('FromStore', 'From Store', 'WIP'), t('VehicleNo', 'Vehicle No'), t('EwayBill', 'E-way Bill / Challan Ref'), c('ChallanValue', 'Challan Value', (_, l) => sum(l, 'Amount'), { money: true }), status(['Sent', 'Partially Received', 'Received'])],
    lines: { table: 'DcSubConOutgoingSub', title: 'Material sent', fields: [item(), process(), n('Qty', 'Qty', { required: true, default: 1 }), m('Rate', 'Declared Rate'), amount] },
    stock: (h, lines) => [...moves(lines, 'Item', 'Qty', h.FromStore, -1), ...moves(lines, 'Item', 'Qty', 'SC', 1)],
    from: { frmSubConPO: (src, lines) => ({ header: { Vendor: src.Vendor, SubConPORef: src.POId }, lines: copyLines(lines, l => ({ Item: l.Item, Process: l.Process, Qty: l.Qty, Rate: l.Rate })) }) },
    after: (h, _l, ctx) => setStatus(ctx, 'SubConPO', 'POId', h.SubConPORef, 'Material Sent') },
  { id: 'frmDCSubConIn', title: 'Subcontract Inward DC', menu: 'SubContract', tables: ['DCSubConIncoming', 'DCSubConIncomingSub'], key: 'DcId', prefix: 'SCDC-I', docDate: 'Date', description: 'Receive processed parts. Stock moves SubCon Store → Quarantine for inspection.',
    fields: [d('Date', 'Receipt Date'), vendor(), ref('SubConPORef', 'Subcontract PO', 'SubConPO', 'POId', 'Vendor'), ref('DCOutRef', 'Outward DC Ref', 'DCSubConOutgoing', 'DcId', 'Vendor'), t('VendorDCNo', 'Vendor Challan No'), store('ToStore', 'Receive Into', 'QRT'), c('TotalReceived', 'Total Received', (_, l) => sum(l, 'ReceivedQty')), status(['Received', 'Inspected', 'Closed'])],
    lines: { table: 'DCSubConIncomingSub', title: 'Material received', fields: [item(), process(), n('SentQty', 'Sent'), n('ReceivedQty', 'Received', { required: true }), n('ScrapQty', 'Scrap at Vendor'), c('Balance', 'Balance at Vendor', l => r2(num(l.SentQty) - num(l.ReceivedQty) - num(l.ScrapQty)))] },
    stock: (h, lines) => [...moves(lines, 'Item', 'ReceivedQty', 'SC', -1), ...moves(lines, 'Item', 'ReceivedQty', h.ToStore, 1), ...moves(lines, 'Item', 'ScrapQty', 'SC', -1), ...moves(lines, 'Item', 'ScrapQty', 'SCRAP', 1)],
    from: { frmDCSubConOut: (src, lines) => ({ header: { Vendor: src.Vendor, SubConPORef: src.SubConPORef, DCOutRef: src.DcId }, lines: copyLines(lines, l => ({ Item: l.Item, Process: l.Process, SentQty: l.Qty, ReceivedQty: l.Qty, ScrapQty: 0 })) }) },
    after: (h, _l, ctx) => { setStatus(ctx, 'SubConPO', 'POId', h.SubConPORef, 'Received'); setStatus(ctx, 'DCSubConOutgoing', 'DcId', h.DCOutRef, 'Received') } },
  { id: 'frmInvoiceSC', title: 'Subcontract Bill Verification', menu: 'SubContract', tables: ['SUPPLIER', 'Vendor'], store: 'InvoiceSC', key: 'InvNo', prefix: 'SCB', docDate: 'Date', description: 'Verify subcontractor invoice against inward DC; posts to vendor account.',
    fields: [d('Date', 'Bill Date'), vendor(), t('VendorInvNo', 'Vendor Invoice No', { required: true }), ref('DCInRef', 'Inward DC Ref', 'DCSubConIncoming', 'DcId', 'Vendor'), ref('SubConPORef', 'Subcontract PO', 'SubConPO', 'POId', 'Vendor'), n('GST', 'GST %', { default: 18 }), ...gstTotals, status(['Pending', 'Verified', 'Paid'])],
    lines: { table: 'InvoiceSCSub', title: 'Job work charges', fields: [item(), process(), n('Qty', 'Qty', { required: true }), m('Rate', 'Rate'), amount] },
    from: { frmDCSubConIn: (src, lines, ctx) => ({ header: { Vendor: src.Vendor, DCInRef: src.DcId, SubConPORef: src.SubConPORef }, lines: copyLines(lines, l => ({ Item: l.Item, Process: l.Process, Qty: l.ReceivedQty, Rate: rows(ctx.db, 'SubConPOSub').find(p => p.ParentId === src.SubConPORef && p.Item === l.Item)?.Rate })) }) } },
  { id: 'frmDcSubConStoreCrNote', title: 'Subcontract Store Credit Note', menu: 'SubContract', tables: ['DCSubConIncoming'], store: 'DcSubConStoreCrNote', key: 'Id', prefix: 'SCCN', docDate: 'Date', description: 'Rejected job-work parts returned to subcontractor.',
    fields: [d('Date', 'Date'), vendor(), ref('DCInRef', 'Inward DC Ref', 'DCSubConIncoming', 'DcId', 'Vendor'), item(), n('Qty', 'Rejected Qty', { required: true }), store('FromStore', 'From Store', 'QRT'), m('Rate', 'Rate'), c('Value', 'Credit Value', h => r2(num(h.Qty) * num(h.Rate)), { money: true }), t('Reason', 'Reason', { wide: true })],
    stock: h => moves([h], 'Item', 'Qty', h.FromStore, -1) },
  // ───────── Purchase
  { id: 'frmPurchasePO', title: 'Supplier PO Outward', menu: 'Purchase', tables: ['PurchPO', 'PurchPOSub', 'PurchPOTrack'], key: 'POId', prefix: 'PO', docDate: 'Date', description: 'Formal PO with specs, delivery schedule, GST and payment terms.',
    fields: [d('Date', 'PO Date'), supplier(), d('DeliveryDate', 'Delivery Date', { default: undefined }), t('PaymentTerms', 'Payment Terms', { default: '30 days' }), n('GST', 'GST %', { default: 18 }), m('Freight', 'Freight'), ...gstTotals, status(['Open', 'Partially Received', 'Received', 'Closed', 'Cancelled']), ta('Terms', 'Terms')],
    lines: { table: 'PurchPOSub', title: 'Ordered items', fields: [item(), t('Spec', 'Specification'), n('Qty', 'Qty', { required: true, default: 1 }), uom(), m('Rate', 'Rate'), amount, c('Received', 'Received', (l, _x, ctx) => receivedQty(ctx.db, l.ParentId, l.Item))] } },
  { id: 'frmPurchaseGRN', title: 'Goods Receipt Note (GRN)', menu: 'Purchase', tables: ['Purchase', 'PurchaseSub'], key: 'PurchId', prefix: 'GRN', docDate: 'Date', description: 'Receive material at gate into Quarantine / Inspection store.',
    fields: [d('Date', 'GRN Date'), supplier(), ref('PurchPORef', 'Purchase PO', 'PurchPO', 'POId', 'Supplier'), t('SupplierDCNo', 'Supplier DC / Invoice No'), t('VehicleNo', 'Vehicle No'), store('ToStore', 'Receive Into', 'QRT'), c('GRNValue', 'GRN Value', (_, l) => sum(l, 'Amount'), { money: true }), status(['Awaiting Inspection', 'Inspected', 'Closed'])],
    lines: { table: 'PurchaseSub', title: 'Received items', fields: qtyRateLines },
    stock: (h, lines) => moves(lines, 'Item', 'Qty', h.ToStore, 1),
    from: { frmPurchasePO: (src, lines, ctx) => ({ header: { Supplier: src.Supplier, PurchPORef: src.POId }, lines: copyLines(lines, l => ({ Item: l.Item, Description: l.Spec, Qty: r2(num(l.Qty) - receivedQty(ctx.db, src.POId, l.Item)), UOM: l.UOM, Rate: l.Rate })) }) },
    after: (h, _l, ctx) => { const po = rows(ctx.db, 'PurchPO').find(x => x.POId === h.PurchPORef); if (!po) return; const pending = rows(ctx.db, 'PurchPOSub').filter(l => l.ParentId === po.POId).some(l => receivedQty(ctx.db, po.POId, l.Item) < num(l.Qty)); po.Status = pending ? 'Partially Received' : 'Received' } },
  { id: 'frmInvoicePurch', title: 'Purchase Invoice Clearing', menu: 'Purchase', tables: ['Purchase', 'SUPPLIER'], store: 'InvoicePurch', key: 'InvNo', prefix: 'PB', docDate: 'Date', description: 'Match supplier invoice with GRN and PO rate; posts credit to supplier account.',
    fields: [d('Date', 'Bill Date'), supplier(), t('SupplierInvNo', 'Supplier Invoice No', { required: true }), ref('GRNRef', 'GRN Ref', 'Purchase', 'PurchId', 'Supplier'), ref('PurchPORef', 'Purchase PO', 'PurchPO', 'POId', 'Supplier'), d('DueDate', 'Due Date', { default: undefined }), n('GST', 'GST %', { default: 18 }), m('Freight', 'Freight / Other'), ...gstTotals, status(['Pending', 'Verified', 'Paid'])],
    lines: { table: 'InvoicePurchSub', title: 'Billed items', fields: [...qtyRateLines, c('PORate', 'PO Rate', (l, _x, ctx) => { const po = rows(ctx.db, 'InvoicePurch').find(i => i.InvNo === l.ParentId)?.PurchPORef; return rows(ctx.db, 'PurchPOSub').find(p => p.ParentId === po && p.Item === l.Item)?.Rate ?? '' }, { money: true })] },
    from: { frmPurchaseGRN: (src, lines) => ({ header: { Supplier: src.Supplier, GRNRef: src.PurchId, PurchPORef: src.PurchPORef, SupplierInvNo: src.SupplierDCNo }, lines: copyLines(lines, l => ({ Item: l.Item, Description: l.Description, Qty: l.Qty, UOM: l.UOM, Rate: l.Rate })) }) },
    after: (h, _l, ctx) => setStatus(ctx, 'Purchase', 'PurchId', h.GRNRef, 'Closed') },
  { id: 'frmPurchStoreCrNote', title: 'Purchase Store Credit Note', menu: 'Purchase', tables: ['STORE', 'PurchStoreCrNote'], store: 'PurchStoreCrNote', key: 'Id', prefix: 'PCN', docDate: 'Date', description: 'Rejected material returned to supplier; reduces quarantine stock and supplier balance.',
    fields: [d('Date', 'Date'), supplier(), ref('GRNRef', 'GRN Ref', 'Purchase', 'PurchId', 'Supplier'), item(), n('Qty', 'Rejected Qty', { required: true }), store('FromStore', 'From Store', 'QRT'), m('Rate', 'Rate'), c('Value', 'Credit Value', h => r2(num(h.Qty) * num(h.Rate)), { money: true }), t('Reason', 'Reason', { wide: true })],
    stock: h => moves([h], 'Item', 'Qty', h.FromStore, -1) },
  // ───────── Stores
  { id: 'frmStock', title: 'Real-Time Stock Status', menu: 'Stores', tables: ['STORE', 'Stores', 'Item'], key: 'storeID', description: 'Stock balances across all store locations with valuation at standard rate.', fields: [],
    report: { run: ctx => ({ columns: ['storeID', 'StoreName', 'ItemId', 'ItemName', 'UOM', 'Qty', 'Rate', 'Value', 'Reorder'], rows: stockMatrix(ctx.db).filter(r => r.Qty !== 0).map(r => { const it = rows(ctx.db, 'Item').find(i => i.ItemId === r.ItemId) || {}; return { ...r, StoreName: lookupName(ctx.db, 'Stores', 'storeID', 'StoreName', r.storeID), ItemName: it.ItemName, UOM: it.UOM, Rate: it.Rate, Value: r2(r.Qty * num(it.Rate)), Reorder: stockBalance(ctx.db, r.ItemId) < num(it.ReorderLevel) ? 'BELOW REORDER' : '' } }) }) } },
  { id: 'frmStockDetails', title: 'Detailed Bin Stock', menu: 'Stores', tables: ['STORE', 'ItemSub'], key: 'ItemId', description: 'Bin card: every movement with running balance.', fields: [],
    report: { params: [item('Item', 'Item')], run: (ctx, p) => { let bal = 0; return { columns: ['Date', 'storeID', 'RefForm', 'RefId', 'In', 'Out', 'Balance', 'Remarks'], rows: rows(ctx.db, 'StockLedger').filter(l => !p.Item || l.ItemId === p.Item).sort((a, b) => String(a.Date).localeCompare(String(b.Date))).map(l => { bal = r2(bal + num(l.Qty)); return { Date: l.Date, storeID: l.storeID, RefForm: l.RefForm, RefId: l.RefId, In: l.Qty > 0 ? l.Qty : '', Out: l.Qty < 0 ? -l.Qty : '', Balance: bal, Remarks: l.Remarks } }) } } } },
  { id: 'frmStockIssue', title: 'Material Issue Note (MIN)', menu: 'Stores', tables: ['StoreIss', 'StoreIssSub', 'MatlIssNote'], key: 'StoreIssId', prefix: 'MIN', docDate: 'Date', description: 'Issue RM to shop floor against an IWO: RM stock down, WIP stock up.',
    fields: [d('Date', 'Issue Date'), ref('IWORef', 'IWO / Job Card', 'ProdnIWOIss', 'Id', 'Item', { required: true }), store('FromStore', 'From Store', 'RM'), store('ToStore', 'To Store', 'WIP'), staff('IssuedTo', 'Issued To'), ta('Remarks', 'Remarks')],
    lines: { table: 'StoreIssSub', title: 'Issued material', fields: [item(), n('Qty', 'Qty', { required: true, default: 1 }), uom(), c('Available', 'Available in From Store', (l, _x, ctx) => { const h = rows(ctx.db, 'StoreIss').find(x => x.StoreIssId === l.ParentId); return stockBalance(ctx.db, l.Item, h?.FromStore || 'RM') })] },
    stock: (h, lines) => [...moves(lines, 'Item', 'Qty', h.FromStore, -1), ...moves(lines, 'Item', 'Qty', h.ToStore, 1)],
    from: { frmProdnWOIssue: (src, _l, ctx) => ({ header: { IWORef: src.Id, IssuedTo: src.Operator }, lines: explodeBOM(ctx.db, src.Item, num(src.Qty)).filter(e => e.Type === 'Raw Material' || e.Type === 'Bought-out').map(e => ({ Item: e.ItemId, Qty: e.Qty })) }) } },
  { id: 'frmStoreInterTrans', title: 'Inter-Store Stock Transfer', menu: 'Stores', tables: ['StoreInterTrans', 'StoreInterTransSub'], key: 'Id', prefix: 'STT', docDate: 'Date', description: 'Move stock between stores with movement audit trail.',
    fields: [d('Date', 'Transfer Date'), store('FromStore', 'From Store', 'QRT'), store('ToStore', 'To Store', 'RM'), staff('AuthorisedBy', 'Authorised By'), ta('Remarks', 'Remarks')],
    lines: { table: 'StoreInterTransSub', title: 'Transferred items', fields: [item(), n('Qty', 'Qty', { required: true, default: 1 }), uom(), t('Remarks', 'Remarks')] },
    stock: (h, lines) => [...moves(lines, 'Item', 'Qty', h.FromStore, -1), ...moves(lines, 'Item', 'Qty', h.ToStore, 1)] },
  { id: 'frmProdnStoreCrNote', title: 'Production Excess Return', menu: 'Stores', tables: ['STORE', 'ProdnStoreCrNote'], store: 'ProdnStoreCrNote', key: 'Id', prefix: 'PRN', docDate: 'Date', description: 'Excess material returned from shop floor to store.',
    fields: [d('Date', 'Date'), ref('IWORef', 'IWO Ref', 'ProdnIWOIss', 'Id', 'Item'), store('FromStore', 'From Store', 'WIP'), store('ToStore', 'To Store', 'RM'), ta('Remarks', 'Remarks')],
    lines: { table: 'ProdnStoreCrNoteSub', title: 'Returned material', fields: [item(), n('Qty', 'Qty', { required: true, default: 1 }), uom()] },
    stock: (h, lines) => [...moves(lines, 'Item', 'Qty', h.FromStore, -1), ...moves(lines, 'Item', 'Qty', h.ToStore, 1)] },
  { id: 'frmToolCrib', title: 'Tool Crib Inventory', menu: 'Stores', tables: ['TOOLCRIB'], key: 'entryID', prefix: 'TC', docDate: 'Date', description: 'Tool issue to operator, return, wear and re-grind history.',
    fields: [d('Date', 'Date'), item('Tool', 'Tool'), s('TxnType', 'Transaction', ['Issue', 'Return', 'Re-grind', 'Scrap']), staff('Operator', 'Operator'), machine(), n('Qty', 'Qty', { required: true, default: 1 }), s('Condition', 'Condition', ['New', 'Good', 'Worn', 'Damaged']), c('CribStock', 'Tool Crib Stock', (h, _l, ctx) => stockBalance(ctx.db, h.Tool, 'TOOL')), ta('Remarks', 'Remarks')],
    stock: h => h.TxnType === 'Issue' ? [...moves([h], 'Tool', 'Qty', 'TOOL', -1), ...moves([h], 'Tool', 'Qty', 'WIP', 1)] : h.TxnType === 'Return' ? [...moves([h], 'Tool', 'Qty', 'WIP', -1), ...moves([h], 'Tool', 'Qty', 'TOOL', 1)] : h.TxnType === 'Scrap' ? [...moves([h], 'Tool', 'Qty', 'TOOL', -1), ...moves([h], 'Tool', 'Qty', 'SCRAP', 1)] : [] },
  { id: 'frmStkRedDefine', title: 'Stock Reduction & Wastage', menu: 'Stores', tables: ['STORE'], store: 'StkRedDefine', key: 'Id', prefix: 'SR', docDate: 'Date', description: 'Stock reductions for wastage, scrap and adjustments.',
    fields: [d('Date', 'Date'), store('Store', 'Store', 'RM'), item(), n('Qty', 'Reduce Qty', { required: true }), s('Reason', 'Reason', ['Wastage', 'Scrap', 'Physical Count Adjustment', 'Damage', 'Expiry']), staff('AuthorisedBy', 'Authorised By'), ta('Remarks', 'Remarks')],
    stock: h => [...moves([h], 'Item', 'Qty', h.Store, -1), ...(h.Reason === 'Scrap' || h.Reason === 'Wastage' ? moves([h], 'Item', 'Qty', 'SCRAP', 1) : [])] },
  // ───────── Dispatch & sales accounting
  { id: 'frmDCOutgoing', title: 'Outward Delivery Challan', menu: 'Dispatch', tables: ['DCOUTGOINGINV', 'DcOutgoingSubInv'], key: 'DcId', prefix: 'DC', docDate: 'Date', description: 'Dispatch finished goods; reduces FG stock and updates customer PO fulfilled qty.',
    fields: [d('Date', 'DC Date'), customer(), ref('MfgPORef', 'Customer PO', 'MfgPO', 'POId', 'CustPONo', { required: true }), store('FromStore', 'From Store', 'FG'), t('VehicleNo', 'Vehicle No'), t('LRNo', 'LR / E-way Bill No'), t('Transporter', 'Transporter'), c('DCValue', 'DC Value', (_, l) => sum(l, 'Amount'), { money: true }), status(['Dispatched', 'Delivered', 'Invoiced'])],
    lines: { table: 'DcOutgoingSubInv', title: 'Dispatched items', fields: [...qtyRateLines, c('FGStock', 'FG Stock', (l, _x, ctx) => stockBalance(ctx.db, l.Item, 'FG'))] },
    stock: (h, lines) => moves(lines, 'Item', 'Qty', h.FromStore, -1),
    from: { frmMfgPO: (src, lines, ctx) => ({ header: { Customer: src.Customer, MfgPORef: src.POId }, lines: copyLines(lines, l => ({ Item: l.Item, Description: l.Description, Qty: Math.max(0, r2(num(l.Qty) - dispatchedQty(ctx.db, src.POId, l.Item))), UOM: l.UOM, Rate: l.Rate })) }) },
    after: (h, _l, ctx) => { const po = rows(ctx.db, 'MfgPO').find(x => x.POId === h.MfgPORef); if (!po) return; const pending = rows(ctx.db, 'MfgPOSub').filter(l => l.ParentId === po.POId).some(l => dispatchedQty(ctx.db, po.POId, l.Item) < num(l.Qty)); po.Status = pending ? 'Partially Dispatched' : 'Closed' } },
  { id: 'frmInvoice', title: 'Sales Tax Invoice', menu: 'Dispatch', tables: ['DCINV', 'DCINVSUB', 'Customer'], key: 'DcinvId', prefix: 'INV', docDate: 'Date', description: 'GST tax invoice against delivery challans; updates customer outstanding.',
    fields: [d('Date', 'Invoice Date'), customer(), ref('DCRef', 'Delivery Challan', 'DCOUTGOINGINV', 'DcId', 'Customer'), ref('MfgPORef', 'Customer PO', 'MfgPO', 'POId', 'CustPONo'), t('PaymentTerms', 'Payment Terms', { default: '30 days' }), d('DueDate', 'Due Date', { default: undefined }), n('GST', 'GST %', { default: 18 }), m('Freight', 'Freight / Packing'), ...gstTotals, c('CustOutstanding', 'Customer Outstanding', (h, _l, ctx) => customerOutstanding(ctx.db, h.Customer), { money: true }), status(['Issued', 'Part Paid', 'Paid', 'Cancelled'])],
    lines: { table: 'DCINVSUB', title: 'Invoiced items', fields: [...qtyRateLines, t('HSN', 'HSN')] },
    from: { frmDCOutgoing: (src, lines, ctx) => ({ header: { Customer: src.Customer, DCRef: src.DcId, MfgPORef: src.MfgPORef, GST: rows(ctx.db, 'MfgPO').find(p => p.POId === src.MfgPORef)?.GST ?? 18 }, lines: copyLines(lines, l => ({ Item: l.Item, Description: l.Description, Qty: l.Qty, UOM: l.UOM, Rate: l.Rate, HSN: rows(ctx.db, 'Item').find(i => i.ItemId === l.Item)?.HSN })) }) },
    after: (h, _l, ctx) => setStatus(ctx, 'DCOUTGOINGINV', 'DcId', h.DCRef, 'Invoiced') },
  { id: 'frmSCNGen', title: 'Sales Credit Note', menu: 'Dispatch', tables: ['SCNGen', 'SCNGenSub'], key: 'Id', prefix: 'SCN', docDate: 'Date', description: 'Customer sales return credit note; goods return to store, customer balance reduced.',
    fields: [d('Date', 'Date'), customer(), ref('InvoiceRef', 'Against Invoice', 'DCINV', 'DcinvId', 'Customer', { required: true }), store('ToStore', 'Return Into Store', 'QRT'), n('GST', 'GST %', { default: 18 }), ...gstTotals, t('Reason', 'Reason', { wide: true })],
    lines: { table: 'SCNGenSub', title: 'Returned items', fields: qtyRateLines },
    stock: (h, lines) => moves(lines, 'Item', 'Qty', h.ToStore, 1),
    from: { frmInvoice: (src, lines) => ({ header: { Customer: src.Customer, InvoiceRef: src.DcinvId, GST: src.GST }, lines: copyLines(lines, l => ({ Item: l.Item, Description: l.Description, Qty: l.Qty, UOM: l.UOM, Rate: l.Rate })) }) } },
  { id: 'frmDbCrNote', title: 'Debit / Credit Notes', menu: 'Dispatch', tables: ['DbCrNote'], key: 'Id', prefix: 'DCN', docDate: 'Date', description: 'Financial rate adjustments and commercial discounts.',
    fields: [d('Date', 'Date'), s('NoteType', 'Note Type', ['Debit Note', 'Credit Note']), s('PartyType', 'Party Type', ['Customer', 'Supplier', 'Vendor']), t('Party', 'Party Code', { required: true }), t('RefDoc', 'Against Document'), m('Amount', 'Amount', { required: true }), s('Reason', 'Reason', ['Rate Difference', 'Commercial Discount', 'Quality Deduction', 'Freight', 'Other']), ta('Narration', 'Narration')] },
  { id: 'frmAdvAdjust', title: 'Advance Payment Adjust', menu: 'Dispatch', tables: ['Customer', 'Receipts', 'AdvAdjust'], store: 'AdvAdjust', key: 'Id', prefix: 'ADJ', docDate: 'Date', description: 'Adjust customer advance receipts against outstanding invoices.',
    fields: [d('Date', 'Date'), customer(), ref('ReceiptRef', 'Advance Receipt', 'Receipts', 'Id', 'Amount', { required: true }), ref('InvoiceRef', 'Against Invoice', 'DCINV', 'DcinvId', 'GrandTotal', { required: true }), m('Amount', 'Adjusted Amount', { required: true }), c('CustOutstanding', 'Customer Outstanding', (h, _l, ctx) => customerOutstanding(ctx.db, h.Customer), { money: true }), ta('Narration', 'Narration')] },
  // ───────── Quality
  { id: 'frmInspection', title: 'Common Inspection Log', menu: 'Quality', tables: ['Inspection'], key: 'Id', prefix: 'QC', docDate: 'Date', description: 'General quality inspection ledger.',
    fields: [d('Date', 'Date'), s('InspectionType', 'Type', ['Incoming', 'In-Process', 'Final', 'Subcontract', 'Customer Return']), t('RefDoc', 'Reference Document'), item(), n('LotQty', 'Lot Qty'), n('SampleQty', 'Sample Qty'), n('AcceptedQty', 'Accepted'), n('RejectedQty', 'Rejected'), staff('Inspector', 'Inspector'), s('Result', 'Result', ['Accepted', 'Rejected', 'Conditional']), ta('Remarks', 'Remarks')] },
  { id: 'frmInspectionIn', title: 'Incoming Quality Clearance', menu: 'Quality', tables: ['InspectionIn', 'STORE'], key: 'Id', prefix: 'IQC', docDate: 'Date', description: 'Inspect GRN material vs spec / CoA. Accepted qty moves Quarantine → RM Store.',
    fields: [d('Date', 'Inspection Date'), ref('GRNRef', 'GRN Ref', 'Purchase', 'PurchId', 'Supplier', { required: true }), supplier(), store('FromStore', 'Inspect From', 'QRT'), store('ToStore', 'Accepted To', 'RM'), t('CoANo', 'Certificate of Analysis No'), staff('Inspector', 'Inspector'), c('TotalAccepted', 'Total Accepted', (_, l) => sum(l, 'AcceptedQty')), c('TotalRejected', 'Total Rejected', (_, l) => sum(l, 'RejectedQty')), s('Result', 'Result', ['Accepted', 'Rejected', 'Partially Accepted'])],
    lines: { table: 'InspectionInSub', title: 'Inspected items', fields: [item(), n('InspectedQty', 'Inspected', { required: true }), n('AcceptedQty', 'Accepted', { required: true }), n('RejectedQty', 'Rejected'), t('Parameters', 'Parameters Checked'), t('Observation', 'Observation')] },
    stock: (h, lines) => [...moves(lines, 'Item', 'AcceptedQty', h.FromStore, -1), ...moves(lines, 'Item', 'AcceptedQty', h.ToStore, 1)],
    from: { frmPurchaseGRN: (src, lines) => ({ header: { GRNRef: src.PurchId, Supplier: src.Supplier, FromStore: src.ToStore }, lines: copyLines(lines, l => ({ Item: l.Item, InspectedQty: l.Qty, AcceptedQty: l.Qty, RejectedQty: 0 })) }) },
    after: (h, _l, ctx) => setStatus(ctx, 'Purchase', 'PurchId', h.GRNRef, 'Inspected') },
  { id: 'frmInspectionInde', title: 'In-Process Quality Inspection', menu: 'Quality', tables: ['InspectionInde', 'Inspection'], key: 'Id', prefix: 'IPQ', docDate: 'Date', description: 'Dimensional checks during production runs and before packing.',
    fields: [d('Date', 'Date'), ref('IWORef', 'IWO / Job Card', 'ProdnIWOIss', 'Id', 'Item'), item(), process(), machine(), s('Stage', 'Stage', ['First-off', 'In-Process', 'Final', 'Pre-dispatch']), n('SampleSize', 'Sample Size'), staff('Inspector', 'Inspector'), c('Result', 'Result', (_, l) => l.length && l.every(x => x.Result !== 'NOT OK') ? 'OK' : l.length ? 'NOT OK' : ''), ta('Remarks', 'Remarks')],
    lines: { table: 'InspectionIndeSub', title: 'Dimensional checks', fields: [t('Parameter', 'Parameter', { required: true }), t('Spec', 'Specification'), t('Instrument', 'Instrument'), t('Measured', 'Measured'), s('Result', 'Result', ['OK', 'NOT OK'])] },
    from: { frmProdnWOIssue: (src, lines) => ({ header: { IWORef: src.Id, Item: src.Item, Process: lines[0]?.Process, Machine: lines[0]?.Machine } }) } },
  { id: 'frmInspectionSC', title: 'Subcontract Quality Clearance', menu: 'Quality', tables: ['InspectionSC'], key: 'Id', prefix: 'SCQ', docDate: 'Date', description: 'Inspect job-work parts; accepted qty moves Quarantine → destination store.',
    fields: [d('Date', 'Date'), ref('DCInRef', 'Inward DC Ref', 'DCSubConIncoming', 'DcId', 'Vendor', { required: true }), vendor(), store('FromStore', 'Inspect From', 'QRT'), store('ToStore', 'Accepted To', 'WIP'), staff('Inspector', 'Inspector'), c('TotalAccepted', 'Total Accepted', (_, l) => sum(l, 'AcceptedQty')), c('TotalRework', 'Total Rework', (_, l) => sum(l, 'ReworkQty')), c('TotalScrap', 'Total Scrap', (_, l) => sum(l, 'ScrapQty'))],
    lines: { table: 'InspectionSCSub', title: 'Inspected items', fields: [item(), process(), n('ReceivedQty', 'Received'), n('AcceptedQty', 'Accepted', { required: true }), n('ReworkQty', 'Rework'), n('ScrapQty', 'Scrap'), t('Remarks', 'Remarks')] },
    stock: (h, lines) => [...moves(lines, 'Item', 'AcceptedQty', h.FromStore, -1), ...moves(lines, 'Item', 'AcceptedQty', h.ToStore, 1), ...moves(lines, 'Item', 'ScrapQty', h.FromStore, -1), ...moves(lines, 'Item', 'ScrapQty', 'SCRAP', 1)],
    from: { frmDCSubConIn: (src, lines) => ({ header: { DCInRef: src.DcId, Vendor: src.Vendor, FromStore: src.ToStore }, lines: copyLines(lines, l => ({ Item: l.Item, Process: l.Process, ReceivedQty: l.ReceivedQty, AcceptedQty: l.ReceivedQty, ReworkQty: 0, ScrapQty: 0 })) }) },
    after: (h, _l, ctx) => setStatus(ctx, 'DCSubConIncoming', 'DcId', h.DCInRef, 'Inspected') },
  { id: 'frmRejection', title: 'Rejection & Scrap Control', menu: 'Quality', tables: ['RESULTS', 'RejRework'], store: 'RejRework', key: 'Id', prefix: 'REJ', docDate: 'Date', description: 'Root cause, rework authorisation and scrap write-off.',
    fields: [d('Date', 'Date'), s('Source', 'Source', ['Shop Floor', 'Incoming GRN', 'Subcontract', 'Customer Return', 'Final Inspection']), t('RefDoc', 'Reference Document'), item(), n('RejectedQty', 'Rejected Qty', { required: true }), s('RootCause', 'Root Cause', ['Operator Error', 'Machine Fault', 'Material Defect', 'Tooling', 'Drawing / Design', 'Handling']), s('Disposition', 'Disposition', ['Rework', 'Scrap', 'Return to Supplier', 'Use As Is', 'Regrade']), n('ReworkQty', 'Rework Qty'), n('ScrapQty', 'Scrap Qty'), m('ScrapValue', 'Scrap Write-off Value'), staff('Responsible', 'Responsible'), status(['Open', 'Rework In Progress', 'Closed']), ta('CorrectiveAction', 'Corrective Action')],
    stock: h => h.Disposition === 'Scrap' && num(h.ScrapQty) > 0 ? [...moves([h], 'Item', 'ScrapQty', 'WIP', -1), ...moves([h], 'Item', 'ScrapQty', 'SCRAP', 1)] : [] },
  { id: 'frmCalibrate', title: 'Equipment Calibration Master', menu: 'Quality', tables: ['Calibrate', 'CalibrateRep'], key: 'Id', prefix: 'CAL', description: 'Calibration register for verniers, micrometers, height gauges and plug gauges.',
    fields: [t('InstrumentCode', 'Instrument Code', { required: true }), t('InstrumentName', 'Instrument Name', { required: true }), s('InstrumentType', 'Type', ['Vernier', 'Micrometer', 'Height Gauge', 'Plug Gauge', 'Dial Gauge', 'Surface Plate', 'Other']), t('Range', 'Range'), t('LeastCount', 'Least Count'), t('SerialNo', 'Serial No'), t('Location', 'Location'), d('LastCalDate', 'Last Calibration Date'), n('FrequencyMonths', 'Frequency (months)', { default: 12 }), c('DueDate', 'Next Due Date', h => addMonths(h.LastCalDate, num(h.FrequencyMonths))), t('Agency', 'Calibration Agency'), t('CertificateNo', 'Certificate No'), status(['Active', 'Out of Service', 'Scrapped'])],
    lines: { table: 'CalibrateRep', title: 'Calibration history', fields: [d('CalDate', 'Calibration Date'), t('Agency', 'Agency'), t('CertificateNo', 'Certificate No'), s('Result', 'Result', ['Pass', 'Fail', 'Adjusted']), t('Remarks', 'Remarks')] } },
  { id: 'frmCalibrateDUE', title: 'Calibration Due Alerts', menu: 'Quality', tables: ['Calibrate'], key: 'Id', description: 'Instruments due or overdue for calibration.', fields: [],
    report: { params: [n('WithinDays', 'Due Within (days)', { default: 30 })], run: (ctx, p) => { const limit = new Date(); limit.setDate(limit.getDate() + (num(p.WithinDays) || 30)); return { columns: ['InstrumentCode', 'InstrumentName', 'InstrumentType', 'Location', 'LastCalDate', 'DueDate', 'DaysLeft', 'Alert'], rows: rows(ctx.db, 'Calibrate').filter(cal => cal.Status === 'Active').map(cal => { const due = addMonths(cal.LastCalDate, num(cal.FrequencyMonths)); const days = Math.ceil((new Date(due).getTime() - Date.now()) / 86400000); return { ...cal, DueDate: due, DaysLeft: days, Alert: days < 0 ? 'OVERDUE' : 'Due soon' } }).filter(r => new Date(r.DueDate) <= limit) } } } },
  // ───────── Maintenance
  { id: 'frmMaintain', title: 'Preventive Maintenance', menu: 'Maintenance', tables: ['MaintainSch', 'Maintenance'], key: 'Id', prefix: 'PM', description: 'Preventive maintenance schedule and checklist.',
    fields: [machine(), s('MaintType', 'Type', ['Preventive', 'Predictive', 'Lubrication', 'Overhaul']), n('FrequencyDays', 'Frequency (days)', { default: 30 }), d('LastDone', 'Last Done'), c('NextDue', 'Next Due', h => addDays(h.LastDone, num(h.FrequencyDays))), staff('Technician', 'Technician'), status(['Scheduled', 'In Progress', 'Completed', 'Skipped']), ta('Remarks', 'Remarks')],
    lines: { table: 'MaintainSchSub', title: 'Checklist', fields: [t('Task', 'Task', { required: true }), ck('Done', 'Done'), t('Remarks', 'Remarks')] } },
  { id: 'frmBrkDnMaint', title: 'Equipment Breakdown Log', menu: 'Maintenance', tables: ['BrkDown', 'Maintenance'], key: 'Id', prefix: 'BD', docDate: 'BreakdownDate', description: 'Breakdown, repair and downtime tracking.',
    fields: [d('BreakdownDate', 'Breakdown Date'), { name: 'StartTime', label: 'Start Time', type: 'time' }, machine(), staff('ReportedBy', 'Reported By'), t('Problem', 'Problem Reported', { wide: true }), s('RootCause', 'Root Cause', ['Electrical', 'Mechanical', 'Hydraulic', 'Operator', 'Tooling', 'Unknown']), t('Action', 'Repair Action', { wide: true }), staff('RepairedBy', 'Repaired By'), d('RepairDate', 'Repair Date', { default: undefined }), { name: 'EndTime', label: 'End Time', type: 'time' }, c('DowntimeHrs', 'Downtime (hrs)', h => downtimeHours(h)), m('SpareCost', 'Spares Cost'), status(['Open', 'Under Repair', 'Closed'])] },
  { id: 'frmMaintainPro', title: 'Repairs & Downtime Tracker', menu: 'Maintenance', tables: ['BrkDown', 'Maintenance'], store: 'MaintainPro', key: 'Id', description: 'Machine-wise breakdown count, downtime and repair cost.', fields: [],
    report: { run: ctx => ({ columns: ['Machine', 'MachineName', 'Breakdowns', 'OpenBreakdowns', 'DowntimeHrs', 'SpareCost', 'NextPM'], rows: rows(ctx.db, 'Machine').map(mc => { const bd = rows(ctx.db, 'BrkDown').filter(b => b.Machine === mc.Id); const pm = rows(ctx.db, 'MaintainSch').filter(p => p.Machine === mc.Id).map(p => addDays(p.LastDone, num(p.FrequencyDays))).sort()[0]; return { Machine: mc.Id, MachineName: mc.MachineName, Breakdowns: bd.length, OpenBreakdowns: bd.filter(b => b.Status !== 'Closed').length, DowntimeHrs: r2(bd.reduce((acc, b) => acc + num(b.DowntimeHrs), 0)), SpareCost: r2(bd.reduce((acc, b) => acc + num(b.SpareCost), 0)), NextPM: pm || '' } }) }) } },
  // ───────── HR & payroll
  { id: 'frmStaff', title: 'Employee Profile Master', menu: 'HR & Payroll', tables: ['STAFF', 'StaffGrouping'], key: 'Id', description: 'Personal info, designation, department, DOJ, bank account and wage structure.',
    fields: [t('Id', 'Employee Code', { required: true }), t('EmpName', 'Employee Name', { required: true }), t('Designation', 'Designation'), s('Department', 'Department', ['Machine Shop', 'Quality', 'Stores', 'Maintenance', 'Production Planning', 'Administration', 'Accounts']), d('DOJ', 'Date of Joining'), d('DOB', 'Date of Birth', { default: undefined }), t('Phone', 'Phone'), t('Address', 'Address', { wide: true }), t('BankAccount', 'Bank Account No'), t('IFSC', 'IFSC'), t('PFNo', 'PF No'), t('ESINo', 'ESI No'), s('WageType', 'Wage Type', ['Monthly', 'Daily', 'Hourly']), m('BasicPay', 'Basic Pay'), m('DA', 'DA'), m('HRA', 'HRA'), m('OtherAllow', 'Other Allowances'), n('PFPct', 'PF %', { default: 12 }), n('ESIPct', 'ESI %', { default: 0.75 }), status(['Active', 'On Leave', 'Resigned'])] },
  { id: 'frmAttendance', title: 'Attendance Logging', menu: 'HR & Payroll', tables: ['Attendance', 'Holidays'], key: 'Id', prefix: 'ATT', docDate: 'Date', description: 'Daily punch times, overtime and leave status.',
    fields: [d('Date', 'Date'), staff(), s('Shift', 'Shift', ['First', 'Second', 'Night', 'General']), { name: 'InTime', label: 'In Time', type: 'time', default: '09:00' }, { name: 'OutTime', label: 'Out Time', type: 'time', default: '17:30' }, n('OTHrs', 'Overtime Hrs'), s('Status', 'Status', ['Present', 'Half Day', 'Absent', 'Leave', 'Holiday', 'Week Off']), t('Remarks', 'Remarks')] },
  { id: 'frmShiftAlloc', title: 'Employee Shift Allocation', menu: 'HR & Payroll', tables: ['ShiftAlloc'], key: 'Id', prefix: 'SHA', docDate: 'FromDate', description: 'Shift assignments (First, Second, Night).',
    fields: [d('FromDate', 'From Date'), d('ToDate', 'To Date', { default: undefined }), staff(), s('Shift', 'Shift', ['First', 'Second', 'Night', 'General']), s('Department', 'Department', ['Machine Shop', 'Quality', 'Stores', 'Maintenance', 'Production Planning', 'Administration', 'Accounts']), t('Remarks', 'Remarks')] },
  { id: 'frmPTDetails', title: 'Professional Tax Slabs', menu: 'HR & Payroll', tables: ['ProfessionalTax'], key: 'Id', description: 'PT slabs used in salary processing.', fields: [t('Id', 'Slab Id', { required: true }), m('SlabFrom', 'Gross From'), m('SlabTo', 'Gross To'), m('PTAmount', 'PT Amount')] },
  { id: 'frmSalary', title: 'Monthly Payroll Processing', menu: 'HR & Payroll', tables: ['Salary', 'SalaryPrint', 'ProfessionalTax'], key: 'Id', prefix: 'SAL', description: 'Gross, basic, DA, HRA, PF, ESI, PT, loan deductions and net pay.',
    fields: [{ name: 'Month', label: 'Salary Month', type: 'month', required: true, default: () => today().slice(0, 7) }, staff(), n('DaysInMonth', 'Days in Month', { default: 30 }),
      c('AttendanceDays', 'Attendance Days (from register)', (h, _l, ctx) => rows(ctx.db, 'Attendance').filter(a => a.Employee === h.Employee && String(a.Date).startsWith(h.Month)).reduce((acc, a) => acc + (a.Status === 'Present' || a.Status === 'Holiday' || a.Status === 'Week Off' ? 1 : a.Status === 'Half Day' ? 0.5 : 0), 0)),
      n('DaysPaid', 'Days Paid', { required: true, default: 30 }), n('OTHrs', 'OT Hours'),
      c('Basic', 'Basic', (h, _l, ctx) => prorate(ctx, h, 'BasicPay'), { money: true }), c('DAAmt', 'DA', (h, _l, ctx) => prorate(ctx, h, 'DA'), { money: true }), c('HRAAmt', 'HRA', (h, _l, ctx) => prorate(ctx, h, 'HRA'), { money: true }), c('OtherAmt', 'Other Allowances', (h, _l, ctx) => prorate(ctx, h, 'OtherAllow'), { money: true }),
      c('OTAmount', 'OT Amount', (h, _l, ctx) => { const st = staffRow(ctx, h.Employee); return r2(num(h.OTHrs) * (num(st.BasicPay) + num(st.DA)) / (num(h.DaysInMonth) || 30) / 8 * 2) }, { money: true }),
      c('Gross', 'Gross Salary', h => r2(num(h.Basic) + num(h.DAAmt) + num(h.HRAAmt) + num(h.OtherAmt) + num(h.OTAmount)), { money: true }),
      c('PF', 'PF', (h, _l, ctx) => r2(num(h.Basic) * num(staffRow(ctx, h.Employee).PFPct) / 100), { money: true }),
      c('ESI', 'ESI', (h, _l, ctx) => num(h.Gross) <= 21000 ? r2(num(h.Gross) * num(staffRow(ctx, h.Employee).ESIPct) / 100) : 0, { money: true }),
      c('PT', 'Professional Tax', (h, _l, ctx) => num(rows(ctx.db, 'ProfessionalTax').find(p => num(h.Gross) >= num(p.SlabFrom) && num(h.Gross) <= num(p.SlabTo))?.PTAmount), { money: true }),
      c('LoanDeduction', 'Loan Deduction', (h, _l, ctx) => r2(rows(ctx.db, 'StaffLoan').filter(l => l.Employee === h.Employee && l.Status === 'Active').reduce((acc, l) => acc + num(l.MonthlyDeduction), 0)), { money: true }),
      m('OtherDeduction', 'Other Deductions'), m('Advance', 'Advance Paid'),
      c('TotalDeductions', 'Total Deductions', h => r2(num(h.PF) + num(h.ESI) + num(h.PT) + num(h.LoanDeduction) + num(h.OtherDeduction) + num(h.Advance)), { money: true }),
      c('NetPay', 'Net Pay', h => r2(num(h.Gross) - num(h.TotalDeductions)), { money: true }), status(['Processed', 'Approved', 'Paid']), s('PaymentMode', 'Payment Mode', ['Bank Transfer', 'Cash', 'Cheque'])] },
  { id: 'frmStaffLoan', title: 'Staff Advance & Loans', menu: 'HR & Payroll', tables: ['StaffLoan', 'StaffLoanDedTrack'], key: 'Id', prefix: 'LN', docDate: 'Date', description: 'Salary advances with monthly instalment deductions.',
    fields: [d('Date', 'Loan Date'), staff(), m('LoanAmount', 'Loan Amount', { required: true }), n('Installments', 'Instalments', { required: true, default: 10 }), c('MonthlyDeduction', 'Monthly Deduction', h => num(h.Installments) ? r2(num(h.LoanAmount) / num(h.Installments)) : 0, { money: true }),
      c('Recovered', 'Recovered (from payroll)', (h, _l, ctx) => r2(rows(ctx.db, 'Salary').filter(sl => sl.Employee === h.Employee && sl.Month >= String(h.Date).slice(0, 7) && sl.Status === 'Paid').length * num(h.MonthlyDeduction)), { money: true }),
      c('Balance', 'Balance', h => r2(Math.max(0, num(h.LoanAmount) - num(h.Recovered))), { money: true }), t('Purpose', 'Purpose', { wide: true }), status(['Active', 'Closed'])] },
  // ───────── Finance
  { id: 'frmReceipts', title: 'Customer Receipt Voucher', menu: 'Finance', tables: ['Receipts', 'Customer'], key: 'Id', prefix: 'RCT', docDate: 'Date', description: 'Incoming payments (Cheque / NEFT / RTGS / Cash); adjusts customer outstanding.',
    fields: [d('Date', 'Receipt Date'), customer(), s('Mode', 'Mode', ['NEFT/RTGS', 'Cheque', 'Cash', 'UPI']), lk('Bank', 'Bank Account', 'Banks', 'Id', 'BankName'), t('RefNo', 'Cheque / UTR No'), ref('InvoiceRef', 'Against Invoice', 'DCINV', 'DcinvId', 'GrandTotal'), m('Amount', 'Amount', { required: true }), m('TDS', 'TDS Deducted'), c('CustOutstanding', 'Customer Outstanding', (h, _l, ctx) => customerOutstanding(ctx.db, h.Customer), { money: true }), ta('Narration', 'Narration')],
    from: { frmInvoice: src => ({ header: { Customer: src.Customer, InvoiceRef: src.DcinvId, Amount: src.GrandTotal } }) },
    after: (h, _l, ctx) => { const inv = rows(ctx.db, 'DCINV').find(x => x.DcinvId === h.InvoiceRef); if (!inv) return; const paid = rows(ctx.db, 'Receipts').filter(r => r.InvoiceRef === inv.DcinvId).reduce((s2, r) => s2 + num(r.Amount) + num(r.TDS), 0); inv.Status = paid >= num(inv.GrandTotal) - 0.01 ? 'Paid' : paid > 0 ? 'Part Paid' : 'Issued' } },
  { id: 'frmPayments', title: 'Vendor Payment Voucher', menu: 'Finance', tables: ['Payments', 'SUPPLIER'], key: 'Id', prefix: 'PAY', docDate: 'Date', description: 'Payments to suppliers and subcontractors against pending bills.',
    fields: [d('Date', 'Payment Date'), s('PartyType', 'Party Type', ['Supplier', 'Vendor']), t('Party', 'Party Code', { required: true }), s('Mode', 'Mode', ['NEFT/RTGS', 'Cheque', 'Cash', 'UPI']), lk('Bank', 'Bank Account', 'Banks', 'Id', 'BankName'), t('RefNo', 'Cheque / UTR No'), t('BillRef', 'Against Bill'), m('Amount', 'Amount', { required: true }), m('TDS', 'TDS Deducted'), c('PartyOutstanding', 'Party Outstanding', (h, _l, ctx) => h.PartyType === 'Vendor' ? supplierOutstanding(ctx.db, 'Vendor', h.Party) : supplierOutstanding(ctx.db, 'Supplier', h.Party), { money: true }), ta('Narration', 'Narration')],
    from: { frmInvoicePurch: src => ({ header: { PartyType: 'Supplier', Party: src.Supplier, BillRef: src.InvNo, Amount: src.GrandTotal } }), frmInvoiceSC: src => ({ header: { PartyType: 'Vendor', Party: src.Vendor, BillRef: src.InvNo, Amount: src.GrandTotal } }) },
    after: (h, _l, ctx) => { setStatus(ctx, 'InvoicePurch', 'InvNo', h.BillRef, 'Paid'); setStatus(ctx, 'InvoiceSC', 'InvNo', h.BillRef, 'Paid') } },
  { id: 'frmBankTrans', title: 'Bank Transaction Register', menu: 'Finance', tables: ['BankTrans', 'Banks'], key: 'Id', prefix: 'BT', docDate: 'Date', description: 'Cheque issues, deposits, bank charges and reconciliation.',
    fields: [d('Date', 'Date'), lk('Bank', 'Bank Account', 'Banks', 'Id', 'BankName', { required: true }), s('TxnType', 'Transaction Type', ['Deposit', 'Cheque Deposit', 'Cheque Issue', 'Withdrawal', 'Bank Charges', 'Interest']), t('RefNo', 'Cheque / Ref No'), t('Party', 'Party'), m('Amount', 'Amount', { required: true }), ck('Reconciled', 'Reconciled with statement'), d('StatementDate', 'Statement Date', { default: undefined }), ta('Narration', 'Narration')] },
  { id: 'frmExpense', title: 'Expense Voucher Entry', menu: 'Finance', tables: ['EXPENSE'], key: 'Id', prefix: 'EXP', docDate: 'Date', description: 'Direct & indirect expenses.',
    fields: [d('Date', 'Date'), s('ExpenseHead', 'Expense Head', ['Electricity', 'Factory Maintenance', 'Consumables', 'Transport', 'Salaries', 'Rent', 'Office & Admin', 'Other']), lk('CostCenter', 'Cost Center', 'CostCenter', 'CostCntrId', 'CostCenterName'), s('PaidBy', 'Paid By', ['Bank', 'Cash']), lk('Bank', 'Bank Account', 'Banks', 'Id', 'BankName'), t('Party', 'Paid To'), t('BillNo', 'Bill No'), m('Amount', 'Amount', { required: true }), m('GSTAmount', 'GST'), c('Total', 'Total', h => r2(num(h.Amount) + num(h.GSTAmount)), { money: true }), ta('Narration', 'Narration')] },
  { id: 'frmIncome', title: 'Income Voucher Entry', menu: 'Finance', tables: ['INCOME'], key: 'Id', prefix: 'INC', docDate: 'Date', description: 'Non-operational and miscellaneous income.',
    fields: [d('Date', 'Date'), s('IncomeHead', 'Income Head', ['Scrap Sale', 'Interest', 'Job Work Income', 'Rent Received', 'Other']), s('ReceivedBy', 'Received By', ['Bank', 'Cash']), lk('Bank', 'Bank Account', 'Banks', 'Id', 'BankName'), t('Party', 'Received From'), m('Amount', 'Amount', { required: true }), m('GSTAmount', 'GST'), c('Total', 'Total', h => r2(num(h.Amount) + num(h.GSTAmount)), { money: true }), ta('Narration', 'Narration')] },
  // ───────── Others
  { id: 'frmLabourPO', title: 'Testing Lab Orders', menu: 'Others', tables: ['LABPO', 'LABPOsub', 'LABPOTrack'], key: 'POId', prefix: 'LAB', docDate: 'Date', description: 'Laboratory testing purchase orders and test delivery.',
    fields: [d('Date', 'PO Date'), t('Laboratory', 'Testing Laboratory', { required: true }), t('RefDoc', 'Reference (GRN / IWO)'), d('ReportDue', 'Report Due', { default: undefined }), c('Total', 'Total', (_, l) => sum(l, 'Amount'), { money: true }), status(['Open', 'Samples Sent', 'Report Received', 'Closed'])],
    lines: { table: 'LABPOsub', title: 'Tests ordered', fields: [item(), s('TestType', 'Test', ['Chemical Composition', 'Hardness', 'Tensile', 'Microstructure', 'Coating Thickness', 'Salt Spray', 'Other']), n('Qty', 'Samples', { default: 1 }), m('Rate', 'Rate'), amount] } },
  { id: 'frmFileCorres', title: 'File Correspondence', menu: 'Others', tables: ['FileCorres'], key: 'Id', prefix: 'FC', docDate: 'Date', description: 'Correspondence and attachment references.',
    fields: [d('Date', 'Date'), s('PartyType', 'Party Type', ['Customer', 'Supplier', 'Vendor', 'Internal', 'Statutory']), t('Party', 'Party'), t('Subject', 'Subject', { required: true, wide: true }), t('RefDoc', 'Reference Document'), t('FileName', 'File Name / Link', { wide: true }), s('Direction', 'Direction', ['Inward', 'Outward']), ta('Notes', 'Notes')] },
  { id: 'frmViewSearch', title: 'Universal Query Engine', menu: 'Others', tables: ['ViewFieldsSrch', 'ViewRights'], key: 'Id', description: 'Search every table in the active financial-year database.', fields: [], custom: 'search' },
  { id: 'frmMisc', title: 'Database Utilities', menu: 'Others', tables: ['errlog', 'Logs'], key: 'entryID', description: 'Backup, restore, compact and audit logs.', fields: [], custom: 'misc' },
]

function addMonths(date: unknown, months: number) { if (!date) return ''; const dt = new Date(String(date)); if (Number.isNaN(dt.getTime())) return ''; dt.setMonth(dt.getMonth() + months); return dt.toISOString().slice(0, 10) }
function addDays(date: unknown, days: number) { if (!date) return ''; const dt = new Date(String(date)); if (Number.isNaN(dt.getTime())) return ''; dt.setDate(dt.getDate() + days); return dt.toISOString().slice(0, 10) }
function downtimeHours(h: Row) {
  if (!h.BreakdownDate || !h.StartTime) return 0
  const start = new Date(`${h.BreakdownDate}T${h.StartTime}`), end = new Date(`${h.RepairDate || h.BreakdownDate}T${h.EndTime || h.StartTime}`)
  return Math.max(0, r2((end.getTime() - start.getTime()) / 3600000))
}
const staffRow = (ctx: Ctx, id: string) => rows(ctx.db, 'STAFF').find(st => st.Id === id) || {}
const prorate = (ctx: Ctx, h: Row, field: string) => r2(num(staffRow(ctx, h.Employee)[field]) * num(h.DaysPaid) / (num(h.DaysInMonth) || 30))

export const formById = (id: string) => FORMS.find(f => f.id === id)
export const storeOf = (def: FormDef) => def.store || def.tables[0]
export const nextForms = (id: string) => FORMS.filter(f => f.from && f.from[id])
// Forms whose lookup fields point at this form's table, for the "linked documents" panel.
export const linkedForms = (def: FormDef) => FORMS.filter(f => f.id !== def.id && f.fields.some(fl => fl.lookup?.table === storeOf(def) && fl.lookup.key === def.key)).map(f => ({ form: f, field: f.fields.find(fl => fl.lookup?.table === storeOf(def))!.name }))
